Bash Scipts to Go Daemon (Linting and initial Go code) (#3)
* Linter from https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322

* Starting to move the BASH scripts to Go so that is can function as a daemon

- Rational:
- Testability - BASH is difficult to unit test
- Robustness - Currently the BASH scripts run as independent scripts rather than a daemon. This makes handling failure harder.

* Linting errors

* Working through the github actions

* Removing linters that the github actions appear to dislike

run golangci-lint
  Running [/home/runner/golangci-lint-1.54.2-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=./system/go-pyrfid-juke-support --config .golangci.yml] in [/home/runner/work/pyrfid-jukebox/pyrfid-jukebox/system/go-pyrfid-juke-support] ...
  level=error msg="Running error: unknown linters: 'gochecksumtype,perfsprint,protogetter,sloglint,testifylint', run 'golangci-lint help linters' to see the list of supported linters"

  Error: golangci-lint exit with code 3
  Ran golangci-lint in 122ms

* Python Linting correction

* Trim trailing WS from CMUS config

* Renaming the action to be encompassing of both the golang linter and python/assorted linter